version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile

  eventmanagerservice:
    image: ${DOCKER_REGISTRY-}eventmanagerservice
    build:
      context: .
      dockerfile: EventManager/EventManagerService/Dockerfile
    depends_on:
      - mssql
      - identityservice

